-- =============================================================================
-- ERP Vendas (Delphi) - db/01_schema.sql
-- Tarefa: T03 (Lote 1) | Origem: RNF-07, ADR-002, SDD.md Secao 5, VISAO-PRODUTO.md Secao 3
--
-- DDL das 5 tabelas do modelo de dados: CLIENTES, PRODUTOS, VENDAS, VENDA_ITENS,
-- FILA_INTEGRACAO (nomes e colunas conforme VISAO-PRODUTO.md Secao 3, adotado sem
-- mudanca por SDD.md Secao 5).
--
-- Este script NAO conecta nem cria o banco, e NAO contem usuario/senha SYSDBA
-- embutidos (GUARDRAILS.md regra 16). Deve ser executado por uma sessao ja
-- conectada ao banco de destino, por exemplo:
--   isql -user SYSDBA -password <senha> caminho\ERPVENDAS.FDB -i db\01_schema.sql
-- ou, em modo embedded local (sem host:, sem prompt de credencial, quando o
-- arquivo do banco ja existe e o processo tem acesso ao arquivo):
--   isql caminho\ERPVENDAS.FDB -i db\01_schema.sql
-- A senha do SYSDBA (ou de um usuario de aplicacao com privilegios minimos,
-- conforme SDD.md Secao 7 "Isolamento") fica fora deste repositorio, em
-- erpvendas.ini (ver config/erpvendas.ini.example) ou informada na linha de
-- comando/variavel de ambiente na hora de rodar - nunca neste arquivo.
-- REQUISITO (RF4-03): o banco DEVE ter sido criado com DEFAULT CHARACTER SET UTF8
-- (ver db/00_criar_banco.sql). Verificacao:
--   SELECT RDB$CHARACTER_SET_NAME FROM RDB$DATABASE;   -- esperado: UTF8
-- Em banco NONE a collation ERPV_CI_AI abaixo nao existe/falha: recrie o banco.
-- Verificar a collation depois: SELECT RDB$COLLATION_NAME FROM RDB$COLLATIONS
--   WHERE RDB$COLLATION_NAME = 'ERPV_CI_AI';
-- =============================================================================

SET SQL DIALECT 3;

-- -----------------------------------------------------------------------------
-- Collation para busca sem caixa e sem acento (RF4-03). Sintaxe Firebird 3.0:
--   CREATE COLLATION nome FOR UTF8 FROM UNICODE CASE INSENSITIVE ACCENT INSENSITIVE;
-- Baseada na collation UNICODE do Firebird (ICU quando disponivel). Se falhar,
-- alternativa: FROM UNICODE_CI_AI (se pre-definida) ou so CASE INSENSITIVE.
-- Executada antes do SET TERM, entao termina com ponto e virgula.
-- -----------------------------------------------------------------------------
CREATE COLLATION ERPV_CI_AI FOR UTF8 FROM UNICODE CASE INSENSITIVE ACCENT INSENSITIVE;
SET TERM ^ ;

-- -----------------------------------------------------------------------------
-- CLIENTES
-- -----------------------------------------------------------------------------
CREATE TABLE CLIENTES (
  ID              INTEGER GENERATED BY DEFAULT AS IDENTITY,
  NOME            VARCHAR(120)  NOT NULL,          -- Nome / Razao Social
  TIPO_PESSOA     CHAR(1)       NOT NULL,          -- 'F' | 'J'
  CPF_CNPJ        VARCHAR(14)   NOT NULL,          -- somente digitos
  ENDERECO        VARCHAR(200),
  TELEFONE        VARCHAR(20),
  EMAIL           VARCHAR(120)  NOT NULL,          -- destino do relatorio
  ATIVO           BOOLEAN       DEFAULT TRUE NOT NULL,
  DATA_CADASTRO   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_CLIENTES PRIMARY KEY (ID),
  CONSTRAINT UQ_CLIENTES_DOC UNIQUE (CPF_CNPJ),
  CONSTRAINT CK_CLIENTES_TIPO CHECK (TIPO_PESSOA IN ('F','J'))
)^

-- -----------------------------------------------------------------------------
-- PRODUTOS
-- -----------------------------------------------------------------------------
CREATE TABLE PRODUTOS (
  ID              INTEGER GENERATED BY DEFAULT AS IDENTITY,
  DESCRICAO       VARCHAR(120)  NOT NULL,
  UNIDADE         VARCHAR(6)    NOT NULL,          -- UN, KG, CX...
  PRECO_UNITARIO  NUMERIC(15,2) NOT NULL,
  CATEGORIA       VARCHAR(60),
  ATIVO           BOOLEAN       DEFAULT TRUE NOT NULL,
  CONSTRAINT PK_PRODUTOS PRIMARY KEY (ID),
  CONSTRAINT CK_PRODUTOS_PRECO CHECK (PRECO_UNITARIO >= 0)
)^

-- -----------------------------------------------------------------------------
-- VENDAS
-- -----------------------------------------------------------------------------
CREATE TABLE VENDAS (
  ID                   INTEGER GENERATED BY DEFAULT AS IDENTITY,   -- "Numero da Venda"
  CLIENTE_ID           INTEGER       NOT NULL,
  DATA_VENDA           TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
  VALOR_TOTAL          NUMERIC(15,2) DEFAULT 0 NOT NULL,
  STATUS               VARCHAR(10)   DEFAULT 'Pendente' NOT NULL,  -- mesmos literais do contrato
  DATA_QUITACAO        TIMESTAMP,                                  -- vem do Financeiro
  MOTIVO_CANCELAMENTO  VARCHAR(255),
  CONSTRAINT PK_VENDAS PRIMARY KEY (ID),
  CONSTRAINT FK_VENDAS_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES (ID),
  CONSTRAINT CK_VENDAS_STATUS CHECK (STATUS IN ('Pendente','Quitada','Cancelada'))
)^

-- -----------------------------------------------------------------------------
-- VENDA_ITENS
-- -----------------------------------------------------------------------------
CREATE TABLE VENDA_ITENS (
  ID              INTEGER GENERATED BY DEFAULT AS IDENTITY,
  VENDA_ID        INTEGER       NOT NULL,
  PRODUTO_ID      INTEGER       NOT NULL,
  QUANTIDADE      INTEGER       NOT NULL,
  PRECO_UNITARIO  NUMERIC(15,2) NOT NULL,          -- snapshot do preco na data da venda
  SUBTOTAL        COMPUTED BY (QUANTIDADE * PRECO_UNITARIO),
  CONSTRAINT PK_VENDA_ITENS PRIMARY KEY (ID),
  CONSTRAINT FK_ITENS_VENDA   FOREIGN KEY (VENDA_ID)   REFERENCES VENDAS (ID) ON DELETE CASCADE,
  CONSTRAINT FK_ITENS_PRODUTO FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS (ID),
  CONSTRAINT CK_ITENS_QTD CHECK (QUANTIDADE > 0)
)^

-- -----------------------------------------------------------------------------
-- FILA_INTEGRACAO - fila simples de reenvio: chamadas ao Financeiro e e-mails
-- que falharam [SUG]
-- -----------------------------------------------------------------------------
CREATE TABLE FILA_INTEGRACAO (
  ID                INTEGER GENERATED BY DEFAULT AS IDENTITY,
  VENDA_ID          INTEGER      NOT NULL,
  TIPO              VARCHAR(12)  NOT NULL,         -- QUITACAO | CANCELAMENTO | EMAIL
  STATUS            VARCHAR(10)  DEFAULT 'PENDENTE' NOT NULL,  -- PENDENTE | CONCLUIDO
  TENTATIVAS        SMALLINT     DEFAULT 0 NOT NULL,
  ULTIMO_ERRO       VARCHAR(500),
  PROXIMA_TENTATIVA TIMESTAMP,
  CRIADO_EM         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONCLUIDO_EM      TIMESTAMP,
  CONSTRAINT PK_FILA PRIMARY KEY (ID),
  CONSTRAINT FK_FILA_VENDA FOREIGN KEY (VENDA_ID) REFERENCES VENDAS (ID),
  CONSTRAINT CK_FILA_TIPO   CHECK (TIPO   IN ('QUITACAO','CANCELAMENTO','EMAIL')),
  CONSTRAINT CK_FILA_STATUS CHECK (STATUS IN ('PENDENTE','CONCLUIDO'))
)^

SET TERM ; ^

-- -----------------------------------------------------------------------------
-- Indices (consultas de filtro/lista do TASK.md: T19/T23 listas com busca/filtro
-- de ativos, T26/T31 lista de vendas filtrada por status/cliente, T37/T50
-- fila filtrada por status/proxima tentativa)
-- -----------------------------------------------------------------------------
CREATE INDEX IDX_VENDAS_CLIENTE ON VENDAS (CLIENTE_ID);
CREATE INDEX IDX_VENDAS_STATUS  ON VENDAS (STATUS);
CREATE INDEX IDX_ITENS_VENDA    ON VENDA_ITENS (VENDA_ID);
CREATE INDEX IDX_FILA_STATUS    ON FILA_INTEGRACAO (STATUS, PROXIMA_TENTATIVA);

-- Fim de db/01_schema.sql
